### PR TITLE
better support for SFML on Android

### PR DESCRIPTION
**Pull request by DennisSc**
Hi,

This commit enables compiling with android NDKs older than 13b, since the need for c++14 was removed altogether ("make_unique< T >" replaced with "unique_ptr< T >(new T())" whis is the same acc. to http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique ), this is advantageous because you (or, at least me) currently cannot reliably compile working SFML binaries in a real-life project with any NDK > 10 with compiler set to 14 (c++14 can cause many strange effects when mixed with old C/CPP code and/or dependencies, sometimes).

The rendering of tiles in the SFMLOrthogonalLayer.hpp example on android didn't work, due to use of the vertex type "Quad" (which Androids OpenGL can't handle), and has been fixed by replacing Quads with two Triangles everywhere (see https://github.com/SFML/SFML/issues/1336#issuecomment-354653915).

The logger has been extended to now also log to Androids logging facility.

"m_chunkSize" in the SFMLOrthogonalLayer.hpp example has been increased to 4096x4096 since this results in no rendering errors (empirically tested, no explanation).

BTW: opening tmx files directly from the "assets" virtual directory on Android does not work - you will need to load them from external media using absolute paths instead (or temporarily copy the files from "assets" to the local cache folder using JNI at runtime, and open them from there, once they reside in a proper file system).

have fun!

### CODE REVIEW

**Comment by fallahn** [comment]
Wow, OK, thanks for this, much appreciated! The lack of C++14 support feels a bit of a regression, but if it improves compatability, then so be it :)

**Comment by DennisSc** [comment]
It does improve dramatically :) 

SFML only works an android when compiled with NDK10, and C++14 support is available starting with NDK13b. Every linker (expectedly) fails when I try to use SFML libraries I compiled with ndk10 in ndk13 (no matter which stl is used) - so the only way to use SFML on android (for me) is currrently to stay on ndk10... thus I had to achieve c++11 compatibility for tmxlite to be able to use itwith SFML on android.

Thanks.

**Comment by fallahn** [comment]
I feel your pain - SFML's android support is very disappointing, even though it is a wonderful library to use - which is why I ended up creating [crogine](https://github.com/fallahn/crogine)

**Comment by DennisSc** [comment]
Nice 👍 
is there any documentation for crogine available?

**Comment by fallahn** [comment]
I never I got around to writing proper docs for it unfortunately, although it has doxy compatible comments. The API strives to be similar to sfml, and uses the same ECS design as [xygine](https://github.com/fallahn/xygine)  :)

**Pull request merged**
